### ISSUE TITLE
The dataset problem

### ISSUE THREAD

**Issue by chrispaul1994** [danielzuegner/gnn-meta-attack#2]
Hi, Daniel：
      The Polblogs dataset cannot be loaded successfully. 
      Could you please proivde the valid dataset? Thanks so much! :)

**Comment by danielzuegner** [comment]
Hi, thanks for pointing this out. It turns out that the dataset is fine but the demo notebook did not correctly consider the case that the node attributes can be missing. Should be fixed in the version I'll push soon. Let me know if the problem persists.
